// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParagonWebAPI;

#nullable disable

namespace ParagonWebAPI.Migrations.MySQL
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20241111050427_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ParagonWebAPI.Types.Organization", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrganizationManagerID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("OrganizationManagerID");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("ParagonWebAPI.Types.User", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsManager")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("OrganizationID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ParagonWebAPI.Types.Organization", b =>
                {
                    b.HasOne("ParagonWebAPI.Types.User", "OrganizationManager")
                        .WithMany()
                        .HasForeignKey("OrganizationManagerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrganizationManager");
                });

            modelBuilder.Entity("ParagonWebAPI.Types.User", b =>
                {
                    b.HasOne("ParagonWebAPI.Types.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationID");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ParagonWebAPI.Types.Organization", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
