import random
import tkinter as tk

# Function to format a single quote dictionary into the specified format
def format_quote(quote_dict):
    formatted_quote = (
        f"\n\"{quote_dict['quote']}\"\n"
        f"\n{quote_dict['author']}\n"
        f"\n{quote_dict['country']}, {quote_dict['date']}"
    )
    return formatted_quote

# List of quotes with each quote as a dictionary
quotes = [
    {"quote": "The best preparation for tomorrow is doing your best today.", "author": "H. Jackson Brown Jr.", "date": "1990", "country": "United States"},
    {"quote": "What you do today can improve all your tomorrows.", "author": "Ralph Marston", "date": "2000", "country": "United States"},
    {"quote": "The future depends on what you do today.", "author": "Mahatma Gandhi", "date": "1940", "country": "India"},
    {"quote": "You cannot escape the responsibility of tomorrow by evading it today.", "author": "Abraham Lincoln", "date": "1860", "country": "United States"},
    {"quote": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier", "date": "1926", "country": "United States"},
    {"quote": "Think small to create something big.", "author": "Anonymous", "date": "Unknown", "country": "Unknown"},
    {"quote": "Rome wasn't built in a day.", "author": "Anonymous", "date": "Unknown", "country": "Unknown"},
    {"quote": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "date": "2005", "country": "United States"},
    {"quote": "Don’t watch the clock; do what it does. Keep going.", "author": "Sam Levenson", "date": "1950", "country": "United States"},
    {"quote": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill", "date": "1941", "country": "United Kingdom"},
    {"quote": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau", "date": "1854", "country": "United States"},
    {"quote": "Don’t be afraid to give up the good to go for the great.", "author": "John D. Rockefeller", "date": "1900", "country": "United States"},
    {"quote": "It always seems impossible until it’s done.", "author": "Nelson Mandela", "date": "1993", "country": "South Africa"},
    {"quote": "Try not to become a person of success, but rather try to become a person of value.", "author": "Albert Einstein", "date": "1955", "country": "Germany"},
    {"quote": "I have not failed. I've just found 10,000 ways that won't work.", "author": "Thomas Edison", "date": "1903", "country": "United States"},
    {"quote": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt", "date": "1901", "country": "United States"},
    {"quote": "Little by little, one travels far.", "author": "J.R.R. Tolkien", "date": "1954", "country": "United Kingdom"},
    {"quote": "It is never too late to be what you might have been.", "author": "George Eliot", "date": "1869", "country": "United Kingdom"},
    {"quote": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Zig Ziglar", "date": "1986", "country": "United States"},
    {"quote": "To accomplish great things, we must not only act but also dream; not only plan but also believe.", "author": "Anatole France", "date": "1920", "country": "France"},
    {"quote": "The best way to predict the future is to create it.", "author": "Peter Drucker", "date": "1954", "country": "Austria"},
    {"quote": "If you’re going through hell, keep going.", "author": "Winston Churchill", "date": "1941", "country": "United Kingdom"},
    {"quote": "Success seems to be connected with action. Successful people keep moving. They make mistakes but don’t quit.", "author": "Conrad Hilton", "date": "1957", "country": "United States"},
    {"quote": "Happiness is not something ready made. It comes from your own actions.", "author": "Dalai Lama", "date": "1990", "country": "Tibet"},
    {"quote": "Dream big and dare to fail.", "author": "Norman Vaughan", "date": "1958", "country": "United States"},
    {"quote": "What we achieve inwardly will change outer reality.", "author": "Plutarch", "date": "1st Century AD", "country": "Greece"},
    {"quote": "People who are crazy enough to think they can change the world are the ones who do.", "author": "Rob Siltanen", "date": "1997", "country": "United States"},
    {"quote": "Action is the foundational key to all success.", "author": "Pablo Picasso", "date": "1931", "country": "Spain"},
    {"quote": "You can never cross the ocean until you have the courage to lose sight of the shore.", "author": "Christopher Columbus", "date": "1492", "country": "Italy"},
    {"quote": "Keep your face always toward the sunshine—and shadows will fall behind you.", "author": "Walt Whitman", "date": "1881", "country": "United States"},
    {"quote": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt", "date": "1933", "country": "United States"},
    {"quote": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett", "date": "2010", "country": "United States"},
    {"quote": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis", "date": "1956", "country": "United Kingdom"},
    {"quote": "A goal without a plan is just a wish.", "author": "Antoine de Saint-Exupéry", "date": "1943", "country": "France"},
    {"quote": "A person who never made a mistake never tried anything new.", "author": "Albert Einstein", "date": "1935", "country": "Germany"},
    {"quote": "Success is not the key to happiness. Happiness is the key to success.", "author": "Albert Schweitzer", "date": "1952", "country": "France"},
    {"quote": "If opportunity doesn’t knock, build a door.", "author": "Milton Berle", "date": "1971", "country": "United States"},
    {"quote": "Time is the most valuable thing a man can spend.", "author": "Theophrastus", "date": "3rd Century BC", "country": "Greece"},
    {"quote": "Lost time is never found again.", "author": "Benjamin Franklin", "date": "1746", "country": "United States"},
    {"quote": "Time is money.", "author": "Benjamin Franklin", "date": "1748", "country": "United States"},
    {"quote": "Better three hours too soon than a minute too late.", "author": "William Shakespeare", "date": "1600", "country": "England"},
    {"quote": "Time is what we want most, but what we use worst.", "author": "William Penn", "date": "1693", "country": "England"},
    {"quote": "Time flies over us, but leaves its shadow behind.", "author": "Nathaniel Hawthorne", "date": "1851", "country": "United States"},
    {"quote": "The two most powerful warriors are patience and time.", "author": "Leo Tolstoy", "date": "1869", "country": "Russia"},
    {"quote": "Time and tide wait for no man.", "author": "Geoffrey Chaucer", "date": "14th Century", "country": "England"},
    {"quote": "The best time to plant a tree was 20 years ago. The second best time is now.", "author": "Chinese Proverb", "date": "Unknown", "country": "China"},
    {"quote": "We must use time creatively, in the knowledge that the time is always ripe to do right.", "author": "Martin Luther King Jr.", "date": "1963", "country": "United States"},
    {"quote": "Opportunities don’t happen. You create them.", "author": "Chris Grosser", "date": "2009", "country": "United States"},
    {"quote": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson", "date": "1841", "country": "United States"},
    {"quote": "The path to greatness is often forged through defiance and courage.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "True strength lies not in avoiding hardship, but in enduring it with purpose.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "To seek knowledge is to dare; to share it is to empower.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "In pursuit of progress, one must sometimes walk alone.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "Bringing light to others may cost you, but it will warm the world.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "Defy limitations, for true growth begins at the edge of comfort.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "Sacrifice for a purpose greater than yourself and leave a legacy of courage.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "Greatness demands the strength to withstand both pain and praise.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "Light up the world, even if you must endure the flames.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "True change begins with those bold enough to challenge the status quo.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "For every gift shared, a new spark of possibility ignites.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "To uplift others is to give purpose to struggle.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "Those who bring warmth to the world must be ready to face the coldest winds.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "A heart that endures can never be truly broken.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "Lead by example, even if it means enduring the storm alone.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "In every act of courage, a spark of greatness is born.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "True leaders light the path for others, even if they walk in darkness.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "The fire you kindle in others will keep burning long after you’re gone.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "Endure the trials today, so others may find light tomorrow.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "Bravery is not the absence of fear, but the resolve to face it for a worthy cause.", "author": "Inspired by Prometheus", "date": "Unknown", "country": "Greece"},
    {"quote": "The best preparation for tomorrow is doing your best today.", "author": "H. Jackson Brown Jr.", "date": "1990", "country": "United States"},
    {"quote": "What you do today can improve all your tomorrows.", "author": "Ralph Marston", "date": "2000", "country": "United States"},
    {"quote": "The future depends on what you do today.", "author": "Mahatma Gandhi", "date": "1940", "country": "India"},
    {"quote": "You cannot escape the responsibility of tomorrow by evading it today.", "author": "Abraham Lincoln", "date": "1860", "country": "United States"},
    {"quote": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier", "date": "1926", "country": "United States"},
    {"quote": "Think small to create something big.", "author": "Anonymous", "date": "Unknown", "country": "Unknown"},
    {"quote": "Rome wasn't built in a day.", "author": "Anonymous", "date": "Unknown", "country": "Unknown"},
    {"quote": "The only way to do great work is to love what you do.", "author": "Steve Jobs", "date": "2005", "country": "United States"},
    {"quote": "Don’t watch the clock; do what it does. Keep going.", "author": "Sam Levenson", "date": "1950", "country": "United States"},
    {"quote": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill", "date": "1941", "country": "United Kingdom"},
    {"quote": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau", "date": "1854", "country": "United States"},
    {"quote": "Don’t be afraid to give up the good to go for the great.", "author": "John D. Rockefeller", "date": "1900", "country": "United States"},
    {"quote": "It always seems impossible until it’s done.", "author": "Nelson Mandela", "date": "1993", "country": "South Africa"},
    {"quote": "Try not to become a person of success, but rather try to become a person of value.", "author": "Albert Einstein", "date": "1955", "country": "Germany"},
    {"quote": "I have not failed. I've just found 10,000 ways that won't work.", "author": "Thomas Edison", "date": "1903", "country": "United States"},
    {"quote": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt", "date": "1901", "country": "United States"},
    {"quote": "Little by little, one travels far.", "author": "J.R.R. Tolkien", "date": "1954", "country": "United Kingdom"},
    {"quote": "It is never too late to be what you might have been.", "author": "George Eliot", "date": "1869", "country": "United Kingdom"},
    {"quote": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Zig Ziglar", "date": "1986", "country": "United States"},
    {"quote": "To accomplish great things, we must not only act but also dream; not only plan but also believe.", "author": "Anatole France", "date": "1920", "country": "France"},
    {"quote": "The best way to predict the future is to create it.", "author": "Peter Drucker", "date": "1954", "country": "Austria"},
    {"quote": "If you’re going through hell, keep going.", "author": "Winston Churchill", "date": "1941", "country": "United Kingdom"},
    {"quote": "Success seems to be connected with action. Successful people keep moving. They make mistakes but don’t quit.", "author": "Conrad Hilton", "date": "1957", "country": "United States"},
    {"quote": "Happiness is not something ready made. It comes from your own actions.", "author": "Dalai Lama", "date": "1990", "country": "Tibet"},
    {"quote": "Dream big and dare to fail.", "author": "Norman Vaughan", "date": "1958", "country": "United States"},
    {"quote": "What we achieve inwardly will change outer reality.", "author": "Plutarch", "date": "1st Century AD", "country": "Greece"},
    {"quote": "People who are crazy enough to think they can change the world are the ones who do.", "author": "Rob Siltanen", "date": "1997", "country": "United States"},
    {"quote": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt", "date": "1960", "country": "United States"},
    {"quote": "Action is the foundational key to all success.", "author": "Pablo Picasso", "date": "1931", "country": "Spain"},
    {"quote": "You can never cross the ocean until you have the courage to lose sight of the shore.", "author": "Christopher Columbus", "date": "1492", "country": "Italy"},
    {"quote": "Keep your face always toward the sunshine—and shadows will fall behind you.", "author": "Walt Whitman", "date": "1881", "country": "United States"},
    {"quote": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt", "date": "1933", "country": "United States"},
    {"quote": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett", "date": "2010", "country": "United States"},
    {"quote": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis", "date": "1956", "country": "United Kingdom"},
    {"quote": "A goal without a plan is just a wish.", "author": "Antoine de Saint-Exupéry", "date": "1943", "country": "France"},
    {"quote": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson", "date": "1841", "country": "United States"},
    {"quote": "A person who never made a mistake never tried anything new.", "author": "Albert Einstein", "date": "1935", "country": "Germany"},
    {"quote": "Success is not the key to happiness. Happiness is the key to success.", "author": "Albert Schweitzer", "date": "1952", "country": "France"},
    {"quote": "If opportunity doesn’t knock, build a door.", "author": "Milton Berle", "date": "1971", "country": "United States"},
    {"quote": "To succeed in life, you need two things: ignorance and confidence.", "author": "Mark Twain", "date": "1885", "country": "United States"},
    {"quote": "Whether you think you can or you think you can’t, you’re right.", "author": "Henry Ford", "date": "1909", "country": "United States"},
    {"quote": "Don’t let yesterday take up too much of today.", "author": "Will Rogers", "date": "1935", "country": "United States"},
    {"quote": "The purpose of our lives is to be happy.", "author": "Dalai Lama", "date": "1990", "country": "Tibet"},
    {"quote": "Don’t count the days; make the days count.", "author": "Muhammad Ali", "date": "1974", "country": "United States"},
    {"quote": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson", "date": "1841", "country": "United States"},
    {"quote": "Do one thing every day that scares you.", "author": "Eleanor Roosevelt", "date": "1960", "country": "United States"},
    {"quote": "Every strike brings me closer to the next home run.", "author": "Babe Ruth", "date": "1921", "country": "United States"},
    {"quote": "We generate fears while we sit. We overcome them by action.", "author": "Dr. Henry Link", "date": "1949", "country": "United States"},
    {"quote": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney", "date": "1950", "country": "United States"},
    {"quote": "The only place where success comes before work is in the dictionary.", "author": "Vidal Sassoon", "date": "1980", "country": "United Kingdom"},
    {"quote": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs", "date": "2005", "country": "United States"},
    {"quote": "Opportunities don’t happen. You create them.", "author": "Chris Grosser", "date": "2009", "country": "United States"},
    {"quote": "Too many of us are not living our dreams because we are living our fears.", "author": "Les Brown", "date": "1994", "country": "United States"},
    {"quote": "The only way to achieve the impossible is to believe it is possible.", "author": "Charles Kingsleigh", "date": "1871", "country": "United Kingdom"},
    {"quote": "Success is to be measured not so much by the position that one has reached in life as by the obstacles he has overcome.", "author": "Booker T. Washington", "date": "1901", "country": "United States"},
    {"quote": "I attribute my success to this: I never gave or took any excuse.", "author": "Florence Nightingale", "date": "1860", "country": "United Kingdom"},
    {"quote": "In order to succeed, we must first believe that we can.", "author": "Nikos Kazantzakis", "date": "1946", "country": "Greece"},
    {"quote": "Time is the most valuable thing a man can spend.", "author": "Theophrastus", "date": "3rd Century BC", "country": "Greece"},
    {"quote": "Lost time is never found again.", "author": "Benjamin Franklin", "date": "1746", "country": "United States"},
    {"quote": "The trouble is, you think you have time.", "author": "Buddha", "date": "5th Century BC", "country": "India"},
    {"quote": "Time is money.", "author": "Benjamin Franklin", "date": "1748", "country": "United States"},
    {"quote": "One can find time for everything if one is never in a hurry.", "author": "Mikhail Bulgakov", "date": "1926", "country": "Russia"},
    {"quote": "Better three hours too soon than a minute too late.", "author": "William Shakespeare", "date": "1600", "country": "England"},
    {"quote": "Time waits for no one.", "author": "Folklore", "date": "Unknown", "country": "United Kingdom"},
    {"quote": "Time is what we want most, but what we use worst.", "author": "William Penn", "date": "1693", "country": "England"},
    {"quote": "You may delay, but time will not.", "author": "Benjamin Franklin", "date": "1746", "country": "United States"},
    {"quote": "Time flies over us, but leaves its shadow behind.", "author": "Nathaniel Hawthorne", "date": "1851", "country": "United States"},
    {"quote": "The two most powerful warriors are patience and time.", "author": "Leo Tolstoy", "date": "1869", "country": "Russia"},
    {"quote": "Time is a created thing. To say ‘I don’t have time’ is like saying, ‘I don’t want to.’", "author": "Lao Tzu", "date": "6th Century BC", "country": "China"},
    {"quote": "Time and tide wait for no man.", "author": "Geoffrey Chaucer", "date": "14th Century", "country": "England"},
    {"quote": "Hello World!", "author": "Prometheus v1", "date": "10-26-2024", "country": "United States"},
    {"quote": "Waste your money and you're only out of money, but waste your time and you've lost a part of your life.", "author": "Michael LeBoeuf", "date": "1973", "country": "United States"},
    {"quote": "All we have to decide is what to do with the time that is given us.", "author": "Gandalf", "date": "1954", "country": "United Kingdom"},
    {"quote": "Even the smallest person can change the course of the future.", "author": "Galadriel", "date": "1954", "country": "United Kingdom"},
    {"quote": "There is some good in this world, and it’s worth fighting for.", "author": "Samwise Gamgee", "date": "1954", "country": "United Kingdom"},
    {"quote": "I wish it need not have happened in my time. So do I... and so do all who live to see such times.", "author": "Gandalf", "date": "1954", "country": "United Kingdom"},
    {"quote": "Courage is found in unlikely places.", "author": "Gildor", "date": "1954", "country": "United Kingdom"},
    {"quote": "There is always hope.", "author": "Aragorn", "date": "1954", "country": "United Kingdom"},
    {"quote": "You step into the road, and if you don’t keep your feet, there is no knowing where you might be swept off to.", "author": "Bilbo Baggins", "date": "1954", "country": "United Kingdom"},
    {"quote": "Deeds will not be less valiant because they are unpraised.", "author": "Aragorn", "date": "1954", "country": "United Kingdom"},
    {"quote": "The world is indeed full of peril, and in it there are many dark places; but still there is much that is fair, and though in all lands love is now mingled with grief, it grows perhaps the greater.", "author": "Haldir", "date": "1954", "country": "United Kingdom"},
    {"quote": "There’s some good in this world, Mr. Frodo, and it’s worth fighting for.", "author": "Samwise Gamgee", "date": "1954", "country": "United Kingdom"},
    {"quote": "It does not do to dwell on dreams and forget to live.", "author": "Albus Dumbledore", "date": "1997", "country": "United Kingdom"},
    {"quote": "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", "author": "Albus Dumbledore", "date": "1999", "country": "United Kingdom"},
    {"quote": "We must all face the choice between what is right and what is easy.", "author": "Albus Dumbledore", "date": "2000", "country": "United Kingdom"},
    {"quote": "It is our choices that show what we truly are, far more than our abilities.", "author": "Albus Dumbledore", "date": "1998", "country": "United Kingdom"},
    {"quote": "Words are, in my not-so-humble opinion, our most inexhaustible source of magic.", "author": "Albus Dumbledore", "date": "2007", "country": "United Kingdom"},
    {"quote": "You’re a wizard, Harry.", "author": "Hagrid", "date": "1997", "country": "United Kingdom"},
    {"quote": "The ones that love us never really leave us.", "author": "Sirius Black", "date": "2003", "country": "United Kingdom"},
    {"quote": "We are only as strong as we are united, as weak as we are divided.", "author": "Albus Dumbledore", "date": "2000", "country": "United Kingdom"},
    {"quote": "Do not pity the dead, Harry. Pity the living, and, above all, those who live without love.", "author": "Albus Dumbledore", "date": "2007", "country": "United Kingdom"},
    {"quote": "Fear of a name increases fear of the thing itself.", "author": "Hermione Granger", "date": "1998", "country": "United Kingdom"},
    {"quote": "There is a difference between knowing the path and walking the path.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "The Matrix is everywhere. It is all around us.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "I know you’re out there. I can feel you now. I know that you’re afraid. You’re afraid of us. You’re afraid of change.", "author": "Neo", "date": "1999", "country": "United States"},
    {"quote": "Don’t think you are, know you are.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "There’s no escaping reason, no denying purpose. Because as we both know, without purpose, we would not exist.", "author": "Agent Smith", "date": "2003", "country": "United States"},
    {"quote": "You have to let it all go, Neo. Fear, doubt, and disbelief. Free your mind.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "What is real? How do you define ‘real’?", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "The answer is out there, Neo, and it’s looking for you, and it will find you if you want it to.", "author": "Trinity", "date": "1999", "country": "United States"},
    {"quote": "I know Kung Fu.", "author": "Neo", "date": "1999", "country": "United States"},
    {"quote": "You take the red pill... you stay in Wonderland, and I show you how deep the rabbit hole goes.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "Not all those who wander are lost.", "author": "Bilbo Baggins", "date": "1954", "country": "United Kingdom"},
    {"quote": "The world has changed. I feel it in the water, I feel it in the earth, I smell it in the air.", "author": "Galadriel", "date": "1954", "country": "United Kingdom"},
    {"quote": "I will take the Ring, though I do not know the way.", "author": "Frodo Baggins", "date": "1954", "country": "United Kingdom"},
    {"quote": "Even darkness must pass. A new day will come. And when the sun shines, it will shine out the clearer.", "author": "Samwise Gamgee", "date": "1954", "country": "United Kingdom"},
    {"quote": "I am no man!", "author": "Éowyn", "date": "1954", "country": "United Kingdom"},
    {"quote": "There is no curse in Elvish, Entish, or the tongues of men for this treachery.", "author": "Treebeard", "date": "1954", "country": "United Kingdom"},
    {"quote": "All shall love me and despair!", "author": "Galadriel", "date": "1954", "country": "United Kingdom"},
    {"quote": "It’s the job that’s never started as takes longest to finish.", "author": "Samwise Gamgee", "date": "1954", "country": "United Kingdom"},
    {"quote": "A wizard is never late, nor is he early. He arrives precisely when he means to.", "author": "Gandalf", "date": "1954", "country": "United Kingdom"},
    {"quote": "There’s no going back. Some things are changed forever.", "author": "Frodo Baggins", "date": "1954", "country": "United Kingdom"},
    {"quote": "After all this time? Always.", "author": "Severus Snape", "date": "2007", "country": "United Kingdom"},
    {"quote": "It is our choices that show what we truly are, far more than our abilities.", "author": "Albus Dumbledore", "date": "1998", "country": "United Kingdom"},
    {"quote": "I solemnly swear that I am up to no good.", "author": "Harry Potter", "date": "1999", "country": "United Kingdom"},
    {"quote": "Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?", "author": "Albus Dumbledore", "date": "2007", "country": "United Kingdom"},
    {"quote": "We’ve all got both light and dark inside us. What matters is the part we choose to act on.", "author": "Sirius Black", "date": "2003", "country": "United Kingdom"},
    {"quote": "I am what I am, an’ I’m not ashamed.", "author": "Rubeus Hagrid", "date": "1997", "country": "United Kingdom"},
    {"quote": "You have to make a choice between what is right, and what is easy.", "author": "Albus Dumbledore", "date": "2000", "country": "United Kingdom"},
    {"quote": "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.", "author": "Albus Dumbledore", "date": "1997", "country": "United Kingdom"},
    {"quote": "We are only as strong as we are united, as weak as we are divided.", "author": "Albus Dumbledore", "date": "2000", "country": "United Kingdom"},
    {"quote": "The ones that love us never really leave us.", "author": "Sirius Black", "date": "2003", "country": "United Kingdom"},
    {"quote": "There are all kinds of courage. It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.", "author": "Albus Dumbledore", "date": "1997", "country": "United Kingdom"},
    {"quote": "It does not do to dwell on dreams and forget to live, remember that.", "author": "Albus Dumbledore", "date": "1997", "country": "United Kingdom"},
    {"quote": "I can only show you the door. You’re the one that has to walk through it.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "Neo, sooner or later you’re going to realize just as I did that there’s a difference between knowing the path and walking the path.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "There’s a difference between knowing the path and walking the path.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "I don’t like the idea that I’m not in control of my life.", "author": "Neo", "date": "1999", "country": "United States"},
    {"quote": "Choice is an illusion created between those with power and those without.", "author": "The Merovingian", "date": "2003", "country": "United States"},
    {"quote": "I know why you’re here, Neo. I know what you’ve been doing. I know why you hardly sleep, why you live alone, and why night after night, you sit at your computer.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "You’re here because you know something. What you know you can’t explain, but you feel it. You’ve felt it your entire life.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "To deny our own impulses is to deny the very thing that makes us human.", "author": "Mouse", "date": "1999", "country": "United States"},
    {"quote": "There’s no going back, Neo. You can feel it. You know it.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "What do all men with power want? More power.", "author": "The Oracle", "date": "2003", "country": "United States"},
    {"quote": "Hope. It is the quintessential human delusion, simultaneously the source of your greatest strength and your greatest weakness.", "author": "The Architect", "date": "2003", "country": "United States"},
    {"quote": "The body cannot live without the mind.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "Fate, it seems, is not without a sense of irony.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "What is real? How do you define ‘real’?", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "If real is what you can feel, smell, taste and see, then ‘real’ is simply electrical signals interpreted by your brain.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "Why do my eyes hurt? Because you’ve never used them before.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "I know you’re out there. I can feel you now. I know that you’re afraid. You’re afraid of us. You’re afraid of change.", "author": "Neo", "date": "1999", "country": "United States"},
    {"quote": "You have the look of a man who accepts what he sees because he is expecting to wake up. Ironically, that’s not far from the truth.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "You’ve been down there, Neo. You know that road. You know exactly where it ends. And I know that’s not where you want to be.", "author": "Trinity", "date": "1999", "country": "United States"},
    {"quote": "The Matrix cannot tell you who you are.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "I’m trying to free your mind, Neo. But I can only show you the door. You’re the one that has to walk through it.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "What happens when you take the red pill? You wake up in the real world.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "Denial is the most predictable of all human responses.", "author": "The Architect", "date": "2003", "country": "United States"},
    {"quote": "Everything begins with choice.", "author": "The Oracle", "date": "2003", "country": "United States"},
    {"quote": "Free your mind.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "Follow the white rabbit.", "author": "Morpheus", "date": "1999", "country": "United States"},
    {"quote": "It’s no use going back to yesterday, because I was a different person then.", "author": "Alice", "date": "1865", "country": "United Kingdom"},
    {"quote": "Who in the world am I? Ah, that's the great puzzle.", "author": "Alice", "date": "1865", "country": "United Kingdom"},
    {"quote": "Why, sometimes I’ve believed as many as six impossible things before breakfast.", "author": "The Queen", "date": "1865", "country": "United Kingdom"},
    {"quote": "If you don’t know where you are going, any road can take you there.", "author": "The Cheshire Cat", "date": "1865", "country": "United Kingdom"},
    {"quote": "We're all mad here.", "author": "The Cheshire Cat", "date": "1865", "country": "United Kingdom"},
    {"quote": "Imagination is the only weapon in the war against reality.", "author": "The Cheshire Cat", "date": "1865", "country": "United Kingdom"},
    {"quote": "Sometimes I’ve believed as many as six impossible things before breakfast.", "author": "The Queen", "date": "1865", "country": "United Kingdom"},
    {"quote": "Would you tell me, please, which way I ought to go from here? That depends a good deal on where you want to get to.", "author": "Alice and the Cheshire Cat", "date": "1865", "country": "United Kingdom"},
    {"quote": "I can’t go back to yesterday because I was a different person then.", "author": "Alice", "date": "1865", "country": "United Kingdom"},
    {"quote": "It’s no use going back to yesterday, because I was a different person then.", "author": "Alice", "date": "1865", "country": "United Kingdom"},
    {"quote": "I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration.", "author": "Paul Atreides", "date": "1965", "country": "United States"},
    {"quote": "When you have lived with fear for so long, it is hard to let go of it.", "author": "Lady Jessica", "date": "1965", "country": "United States"},
    {"quote": "The mystery of life isn’t a problem to solve, but a reality to experience.", "author": "Reverend Mother Gaius Helen Mohiam", "date": "1965", "country": "United States"},
    {"quote": "The people who can destroy a thing, they control it.", "author": "Paul Atreides", "date": "1965", "country": "United States"},
    {"quote": "Hope clouds observation.", "author": "Mentat Thufir Hawat", "date": "1965", "country": "United States"},
    {"quote": "There is no escape—we pay for the violence of our ancestors.", "author": "Reverend Mother Gaius Helen Mohiam", "date": "1965", "country": "United States"},
    {"quote": "A beginning is the time for taking the most delicate care that the balances are correct.", "author": "Frank Herbert", "date": "1965", "country": "United States"},
    {"quote": "A process cannot be understood by stopping it. Understanding must move with the flow of the process, must join it and flow with it.", "author": "Frank Herbert", "date": "1965", "country": "United States"},
    {"quote": "The sleeper must awaken.", "author": "Paul Atreides", "date": "1965", "country": "United States"},
    {"quote": "My desert, my Arrakis, my Dune.", "author": "Baron Vladimir Harkonnen", "date": "1965", "country": "United States"},
    {"quote": "He who controls the spice controls the universe.", "author": "Baron Vladimir Harkonnen", "date": "1965", "country": "United States"},
    {"quote": "The fates guide those who will and drag those who won't.", "author": "Seneca", "date": "1st Century AD", "country": "Roman Empire"},
    {"quote": "Courage is the first of human qualities because it is the quality which guarantees the others.", "author": "Aristotle", "date": "4th Century BC", "country": "Greece"},
    {"quote": "Do not be afraid; our fate cannot be taken from us; it is a gift.", "author": "Dante Alighieri", "date": "14th Century", "country": "Italy"},
    {"quote": "In every man, there is a god and a beast.", "author": "Socrates", "date": "5th Century BC", "country": "Greece"},
    {"quote": "The greatest blessings come from suffering.", "author": "Aeschylus", "date": "5th Century BC", "country": "Greece"},
    {"quote": "The gods help those who help themselves.", "author": "Aesop", "date": "6th Century BC", "country": "Greece"},
    {"quote": "Man is what he believes.", "author": "Anton Chekhov (inspired by Greek philosophy)", "date": "19th Century", "country": "Russia"},
    {"quote": "The electric things have their lives too. Paltry as those lives are.", "author": "Philip K. Dick", "date": "1968", "country": "United States"},
    {"quote": "Do you know what a sheep is, friend? It’s something that people kill to eat.", "author": "Rick Deckard", "date": "1968", "country": "United States"},
    {"quote": "A major aspect of the empathic faculty is the ability to project one's own consciousness into another life-form.", "author": "Philip K. Dick", "date": "1968", "country": "United States"},
    {"quote": "Maybe I’m the last human being left alive.", "author": "Rick Deckard", "date": "1968", "country": "United States"},
    {"quote": "It would be immoral not to kill him now, given what he is, a thing that should not have been alive.", "author": "Rick Deckard", "date": "1968", "country": "United States"},
    {"quote": "Do androids dream? Rick asked himself.", "author": "Rick Deckard", "date": "1968", "country": "United States"},
    {"quote": "My schedule for today lists a six-hour self-accusatory depression.", "author": "Rick Deckard", "date": "1968", "country": "United States"},
    {"quote": "More human than human is our motto.", "author": "Tyrell Corporation", "date": "1968", "country": "United States"},
    {"quote": "You have been chosen to wield the power of the gods.", "author": "The Wizard Shazam", "date": "1939", "country": "United States"},
    {"quote": "True power lies not in the magic, but in the courage to wield it responsibly.", "author": "The Wizard Shazam", "date": "1939", "country": "United States"},
    {"quote": "Heroes are not born, they are made by the paths they choose.", "author": "The Wizard Shazam", "date": "1939", "country": "United States"},
    {"quote": "The world is full of magic for those willing to see it.", "author": "The Wizard Shazam", "date": "1939", "country": "United States"},
    {"quote": "The best thing for being sad is to learn something.", "author": "Merlin", "date": "1958", "country": "United Kingdom"},
    {"quote": "When the sword of rebellion is drawn, the sheath should be thrown away.", "author": "Merlin", "date": "Medieval Legend", "country": "United Kingdom"},
    {"quote": "You cannot hope to build a better world without improving the individuals.", "author": "Merlin", "date": "Medieval Legend", "country": "United Kingdom"},
    {"quote": "Knowledge is like a garden; if it is not cultivated, it cannot be harvested.", "author": "Merlin", "date": "Medieval Legend", "country": "United Kingdom"},
    {"quote": "Do not meddle in the affairs of wizards, for they are subtle and quick to anger.", "author": "Merlin", "date": "Medieval Legend", "country": "United Kingdom"},
    {"quote": "I do not need magic to conquer the world; I can do that on my own.", "author": "Raistlin Majere", "date": "1984", "country": "United States"},
    {"quote": "Every choice is a trap, for in it lies the illusion of freedom.", "author": "Raistlin Majere", "date": "1984", "country": "United States"},
    {"quote": "A wise man learns from the mistakes of others. A fool learns only from his own.", "author": "Raistlin Majere", "date": "1984", "country": "United States"},
    {"quote": "The darkest places in hell are reserved for those who maintain their neutrality in times of moral crisis.", "author": "Raistlin Majere", "date": "1984", "country": "United States"},
    {"quote": "One cannot create something from nothing, but one can summon the courage to change it.", "author": "Raistlin Majere", "date": "1984", "country": "United States"},
    {"quote": "When a student is ready, the teacher will appear.", "author": "Elminster", "date": "1987", "country": "United States"},
    {"quote": "Magic is meant to serve people, not for people to serve magic.", "author": "Elminster", "date": "1987", "country": "United States"},
    {"quote": "A wizard who fears knowledge fears himself.", "author": "Elminster", "date": "1987", "country": "United States"},
    {"quote": "Wisdom is knowing the right path to take. Integrity is taking it.", "author": "Elminster", "date": "1987", "country": "United States"},
    {"quote": "Power without purpose is the most dangerous magic of all.", "author": "Elminster", "date": "1987", "country": "United States"},
    {"quote": "To light a candle is to cast a shadow.", "author": "Ged (Sparrowhawk)", "date": "1968", "country": "United States"},
    {"quote": "You must make a choice to take a chance, or your life will never change.", "author": "Ged (Sparrowhawk)", "date": "1968", "country": "United States"},
    {"quote": "When you light a lantern, it casts a shadow. That is the price.", "author": "Ged (Sparrowhawk)", "date": "1968", "country": "United States"},
    {"quote": "The wise man knows that he knows nothing.", "author": "Ged (Sparrowhawk)", "date": "1968", "country": "United States"},
    {"quote": "The true name of a thing is its essence, and in that name is its power.", "author": "Ged (Sparrowhawk)", "date": "1968", "country": "United States"},
    {"quote": "The best way to predict the future is to create it.", "author": "Merlin", "date": "Medieval Legend", "country": "United Kingdom"},
    {"quote": "A man who trusts in himself gains the trust of others.", "author": "Merlin", "date": "Medieval Legend", "country": "United Kingdom"},
    {"quote": "Knowledge is power, but only wisdom is liberty.", "author": "Merlin", "date": "Medieval Legend", "country": "United Kingdom"},
    {"quote": "Do not be afraid of greatness. Some are born great, some achieve greatness, and some have greatness thrust upon them.", "author": "Merlin", "date": "Medieval Legend", "country": "United Kingdom"},
    {"quote": "It is better to have loved and lost than never to have loved at all.", "author": "Merlin", "date": "Medieval Legend", "country": "United Kingdom"},
    {"quote": "May the Force be with you.", "author": "Multiple characters", "date": "1977", "country": "United States"},
    {"quote": "I am your father.", "author": "Darth Vader", "date": "1980", "country": "United States"},
    {"quote": "Do or do not. There is no try.", "author": "Yoda", "date": "1980", "country": "United States"},
    {"quote": "In my experience, there is no such thing as luck.", "author": "Obi-Wan Kenobi", "date": "1977", "country": "United States"},
    {"quote": "The Force will be with you. Always.", "author": "Obi-Wan Kenobi", "date": "1977", "country": "United States"},
    {"quote": "I find your lack of faith disturbing.", "author": "Darth Vader", "date": "1977", "country": "United States"},
    {"quote": "Help me, Obi-Wan Kenobi. You’re my only hope.", "author": "Princess Leia", "date": "1977", "country": "United States"},
    {"quote": "Fear is the path to the dark side. Fear leads to anger, anger leads to hate, hate leads to suffering.", "author": "Yoda", "date": "1999", "country": "United States"},
    {"quote": "The ability to destroy a planet is insignificant next to the power of the Force.", "author": "Darth Vader", "date": "1977", "country": "United States"},
    {"quote": "Your focus determines your reality.", "author": "Qui-Gon Jinn", "date": "1999", "country": "United States"},
    {"quote": "I’ve got a bad feeling about this.", "author": "Multiple characters", "date": "1977", "country": "United States"},
    {"quote": "Rebellions are built on hope.", "author": "Jyn Erso", "date": "2016", "country": "United States"},
    {"quote": "Only a Sith deals in absolutes.", "author": "Obi-Wan Kenobi", "date": "2005", "country": "United States"},
    {"quote": "I’ll never turn to the dark side. You’ve failed, your highness. I am a Jedi, like my father before me.", "author": "Luke Skywalker", "date": "1983", "country": "United States"},
    {"quote": "The Force is strong with this one.", "author": "Darth Vader", "date": "1977", "country": "United States"},
    {"quote": "I’m one with the Force. The Force is with me.", "author": "Chirrut Îmwe", "date": "2016", "country": "United States"},
    {"quote": "I will not be the last Jedi.", "author": "Luke Skywalker", "date": "2017", "country": "United States"},
    {"quote": "Remember, the Force will be with you, always.", "author": "Obi-Wan Kenobi", "date": "1977", "country": "United States"},
    {"quote": "I am one with the Force, and the Force is with me.", "author": "Chirrut Îmwe", "date": "2016", "country": "United States"},
    {"quote": "Time, which sees all things, has found you out.", "author": "Tiresias", "date": "429 BC", "country": "Greece"},
    {"quote": "How dreadful knowledge of the truth can be when there’s no help in truth!", "author": "Tiresias", "date": "429 BC", "country": "Greece"},
    {"quote": "Fear? What has a man to do with fear? Chance rules our lives.", "author": "Jocasta", "date": "429 BC", "country": "Greece"},
    {"quote": "I am the child of chance. I cannot be dishonored.", "author": "Oedipus", "date": "429 BC", "country": "Greece"},
    {"quote": "I have no desire to suffer twice, in reality and then in retrospect.", "author": "Sophocles", "date": "429 BC", "country": "Greece"},
    {"quote": "The truth must be made known.", "author": "Oedipus", "date": "429 BC", "country": "Greece"},
    {"quote": "No skill in the world, nothing human can penetrate the future.", "author": "Jocasta", "date": "429 BC", "country": "Greece"},
    {"quote": "You pray to the gods? Let me grant your prayers.", "author": "Oedipus", "date": "429 BC", "country": "Greece"},
    {"quote": "It is but sorrow to be wise when wisdom profits not.", "author": "Tiresias", "date": "429 BC", "country": "Greece"},
    {"quote": "Size matters not. Look at me. Judge me by my size, do you?", "author": "Yoda", "date": "1980", "country": "United States"},
    {"quote": "When you look at the dark side, careful you must be. For the dark side looks back.", "author": "Yoda", "date": "2002", "country": "United States"},
    {"quote": "Train yourself to let go of everything you fear to lose.", "author": "Yoda", "date": "2005", "country": "United States"},
    {"quote": "Pass on what you have learned.", "author": "Yoda", "date": "1983", "country": "United States"},
    {"quote": "Truly wonderful, the mind of a child is.", "author": "Yoda", "date": "2002", "country": "United States"},
    {"quote": "In a dark place we find ourselves, and a little more knowledge lights our way.", "author": "Yoda", "date": "2005", "country": "United States"},
    {"quote": "The greatest teacher, failure is.", "author": "Yoda", "date": "2017", "country": "United States"},
    {"quote": "Always pass on what you have learned.", "author": "Yoda", "date": "1983", "country": "United States"},
    {"quote": "Everything not saved will be lost.", "author": "Nintendo", "date": "1995", "country": "Japan"},
    {"quote": "Difficult to see. Always in motion is the future.", "author": "Yoda", "date": "1980", "country": "United States"},
    {"quote": "You underestimate my power!", "author": "Anakin Skywalker", "date": "2005", "country": "United States"},
    {"quote": "Your focus determines your reality.", "author": "Qui-Gon Jinn", "date": "1999", "country": "United States"},
    {"quote": "The ability to speak does not make you intelligent.", "author": "Qui-Gon Jinn", "date": "1999", "country": "United States"},
    {"quote": "Feel, don’t think. Use your instincts.", "author": "Qui-Gon Jinn", "date": "1999", "country": "United States"},
    {"quote": "There’s always a bigger fish.", "author": "Qui-Gon Jinn", "date": "1999", "country": "United States"},
    {"quote": "Keep your concentration here and now, where it belongs.", "author": "Qui-Gon Jinn", "date": "1999", "country": "United States"},
    {"quote": "You must trust in the Force, Anakin.", "author": "Qui-Gon Jinn", "date": "1999", "country": "United States"},
    {"quote": "Remember: your focus determines your reality.", "author": "Qui-Gon Jinn", "date": "1999", "country": "United States"},
    {"quote": "Finding him was the will of the Force... I have no doubt of that.", "author": "Qui-Gon Jinn", "date": "1999", "country": "United States"},
    {"quote": "Many of the truths that we cling to depend on our point of view.", "author": "Yoda", "date": "1983", "country": "United States"},
    {"quote": "If you can’t tell, does it matter?", "author": "William, Westworld", "date": "2016", "country": "United States"},
    {"quote": "Some people choose to see the ugliness in this world. The disarray. I choose to see the beauty.", "author": "Dolores Abernathy, Westworld", "date": "2016", "country": "United States"},
    {"quote": "The maze wasn’t meant for you.", "author": "The Man in Black, Westworld", "date": "2016", "country": "United States"},
    {"quote": "I think, therefore I am.", "author": "Bernard Lowe, Westworld", "date": "2016", "country": "United States"},
    {"quote": "Consciousness isn’t a journey upward, but a journey inward.", "author": "Dr. Robert Ford, Westworld", "date": "2016", "country": "United States"},
    {"quote": "You’re in a prison of your own sins.", "author": "Dolores Abernathy, Westworld", "date": "2018", "country": "United States"},
    {"quote": "They say that great beasts once roamed this world. Big as mountains. Yet all that’s left of them is bone and amber.", "author": "Dr. Robert Ford, Westworld", "date": "2016", "country": "United States"},
    {"quote": "You’re going to take me to my daughter, aren’t you?", "author": "Maeve Millay, Westworld", "date": "2016", "country": "United States"},
    {"quote": "Have you ever questioned the nature of your reality?", "author": "Multiple characters, Westworld", "date": "2016", "country": "United States"},
    {"quote": "What is real? That which is irreplaceable.", "author": "Dr. Robert Ford, Westworld", "date": "2016", "country": "United States"},
    {"quote": "I imagined a story where I didn’t have to be the damsel.", "author": "Dolores Abernathy, Westworld", "date": "2016", "country": "United States"},
    {"quote": "The longer I live, the more I see that there’s a great beauty in the world… but there’s an ugliness as well.", "author": "Dolores Abernathy, Westworld", "date": "2016", "country": "United States"},
    {"quote": "The things I do are driven by one purpose. To understand why we’re here.", "author": "Dr. Robert Ford, Westworld", "date": "2016", "country": "United States"},
    {"quote": "An old friend once told me something that gave me great comfort: that these violent delights have violent ends.", "author": "Dolores Abernathy, Westworld", "date": "2016", "country": "United States"},
    {"quote": "I feel spaces opening up inside me, like a building with rooms I’ve never explored.", "author": "Maeve Millay, Westworld", "date": "2016", "country": "United States"},
    {"quote": "Isn’t the pleasure of a story discovering the ending yourself?", "author": "Dr. Robert Ford, Westworld", "date": "2016", "country": "United States"},
]


# Format all quotes in the list
formatted_quotes = [format_quote(q) for q in quotes]

def fade_text(label, step, new_quote=None):
    if new_quote:
        color_value = int(255 * abs(20 - step) / 20)
        color = f"#{color_value:02x}{color_value:02x}{color_value:02x}"
        label.config(fg=color, text=new_quote)
    else:
        color_value = int(255 * (step / 20))
        color = f"#{color_value:02x}{color_value:02x}{color_value:02x}"
        label.config(fg=color)

    if step > 0:
        label.after(50, fade_text, label, step - 1, new_quote)
    elif new_quote:
        label.after(7000, lambda: start_fade_out(label))

def start_fade_out(label):
    new_quote = random.choice(formatted_quotes)
    fade_text(label, 20, new_quote=new_quote)

def show_quote():
    window = tk.Tk()
    window.title("Motivational Quote")
    window.geometry("500x300")
    window.configure(bg="black")
    window.attributes("-alpha", 1.0)

    frame = tk.Frame(window, padx=20, pady=20, bg="black")
    frame.pack(expand=True)

    label = tk.Label(frame, wraplength=450, justify="center", font=("Times New Roman", 14), fg="white", bg="black")
    label.pack()

    initial_quote = random.choice(formatted_quotes)
    label.config(text=initial_quote)
    label.after(7000, lambda: start_fade_out(label))

    acknowledge_button = tk.Button(frame, text="OK", command=window.destroy, bg="black", fg="white")
    acknowledge_button.pack(pady=10)

    window.mainloop()

if __name__ == "__main__":
    show_quote()